

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aum
 */
public class ExporttoBill extends javax.swing.JFrame {

    /**
     * Creates new form ExporttoBill
     */
    
    ResultSet rs;
    public ExporttoBill() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void exportBill()
    {MessageFormat header=new MessageFormat("ใบเสร็จรับเงิน");
     MessageFormat footer=new MessageFormat("Page{0,number,integer}");
     try
     {
         jTable1.print(JTable.PrintMode.NORMAL,header,footer);
         
     }
     catch(Exception e)
     {e.printStackTrace();
     }
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelphofile = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelusername = new javax.swing.JLabel();
        jLabelpassword = new javax.swing.JLabel();
        jLabeladdress = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelhome = new javax.swing.JLabel();
        jLabelprint = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 50));
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelphofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profilephoto.png"))); // NOI18N
        jPanel1.add(jLabelphofile, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("NAME:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 196, -1, 34));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("USERNAME:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 241, 84, 33));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("PASSWORD:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 292, -1, 32));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("ADDRESS:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 342, -1, 36));

        jLabelusername.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(jLabelusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 241, 154, 33));

        jLabelpassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(jLabelpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 292, 154, 32));
        jPanel1.add(jLabeladdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 342, 153, 36));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 196, 182, 34));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test5.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 440));

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 440, 269));

        jLabelhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        jLabelhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelhomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelhomeMouseExited(evt);
            }
        });
        jPanel2.add(jLabelhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 326, -1, 54));

        jLabelprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/print.png"))); // NOI18N
        jLabelprint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelprintMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelprintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelprintMouseExited(evt);
            }
        });
        jPanel2.add(jLabelprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 326, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test6.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 440));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 10, 480, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setProfile(String name,String username,String password,String address){
       jLabel5.setText(name);
       jLabelusername.setText(username);
       jLabelpassword.setText(password);
       jLabeladdress.setText(address);
    }
    public void getData(){
        String sql="select * from bill";
        try{
            Connection con = NewJFrame.getConnection();
            PreparedStatement pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            if(rs.next())
            {   
                
            }
            
        }
        catch(Exception e){
            e.printStackTrace();
        } 
    }
   
    private void jLabelhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelhomeMouseEntered
       ImageIcon iconexit= new ImageIcon (getClass().getResource("exit1.png"));
       jLabelhome.setIcon(iconexit);          // TODO add your handling code here:
    }//GEN-LAST:event_jLabelhomeMouseEntered

    private void jLabelhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelhomeMouseExited
        ImageIcon iconexit1= new ImageIcon (getClass().getResource("exit.png"));
       jLabelhome.setIcon(iconexit1);// TODO add your handling code here:
    }//GEN-LAST:event_jLabelhomeMouseExited

    private void jLabelprintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelprintMouseEntered
        ImageIcon iconprint= new ImageIcon (getClass().getResource("print1.png"));
       jLabelprint.setIcon(iconprint);       // TODO add your handling code here:
    }//GEN-LAST:event_jLabelprintMouseEntered

    private void jLabelprintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelprintMouseExited
        ImageIcon iconprint1= new ImageIcon (getClass().getResource("print.png"));
       jLabelprint.setIcon(iconprint1);// TODO add your handling code here:
    }//GEN-LAST:event_jLabelprintMouseExited

    private void jLabelhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelhomeMouseClicked
        
        System.exit(0);     // TODO add your handling code here:
    }//GEN-LAST:event_jLabelhomeMouseClicked

    private void jLabelprintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelprintMouseClicked
             
                System.out.print("printbill");
                exportBill();
             // TODO add your handling code here:
    }//GEN-LAST:event_jLabelprintMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExporttoBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExporttoBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExporttoBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExporttoBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExporttoBill().setVisible(true);
            }
        });
    }
    public String name;
    public String username;
    public String password;
    public String address;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabeladdress;
    private javax.swing.JLabel jLabelhome;
    private javax.swing.JLabel jLabelpassword;
    private javax.swing.JLabel jLabelphofile;
    private javax.swing.JLabel jLabelprint;
    private javax.swing.JLabel jLabelusername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    
}
